### ISSUE TITLE
Prep - to do  list

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#11]
- [ ] labs docs on github ~ @jheare 
- [x] identify which labs need animals 
- [x] identify labs where stuff needs ordering
- [ ] identify what equipment we need Jon
- [ ] field trips - Alki 17th ~ @jheare 
- [x] absence policy ~ relationship on peers  ~ excused absence maybe go other section ~ @sr320
- [x] give worksheets point value. ~ @sr320
- [x] Aster model plan ~ @rwaples
- [x] flush out syllabus schedule @sr320
- [ ] plan wet experiment @jheare 
- [x] discussion board assessment  @sr320
- [x] soliciit questions of students - syllabus @sr320

**Comment by sr320** [comment]
please mark off as complete

**Comment by jheare** [comment]
You can view the [supplies](https://github.com/sr320/course-fish310-2015/blob/master/Lab%20Worksheets%20MD/310%20Supplies%20List%202015.md) and [lab animals](https://github.com/sr320/course-fish310-2015/blob/master/Lab%20Worksheets%20MD/310%20Animal%20List%202015.md) lists on github now.
