### ISSUE TITLE
Cnidarian Lab -species

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#15]
Note from Greg
The population of Anthopleura at my usual collecting site still hasn't recovered from the bridge replacement, so I'd rather go with Metridium for the dissection. I think they're better anyway, as they have acontia which are really interesting and great for watching nematocysts fire. I'll still bring a few Anthopleura in as another example of an anthozoan.
With our early spring there are reportedly jellyfish blooms already showing from aerial surveys, so should be no problem getting some of those. Hydroids are usually available year-round off the floats.

**Comment by sr320** [comment]
This labsheet can go ahead and be modified accordingly

**Comment by sr320** [comment]
@rwaples Can you take the lead on revising this worksheet - and we will go over Friday?
Thanks
sheet at https://github.com/sr320/course-fish310-2015/blob/master/Lab%20Worksheets%20MD/Cnidaria%20Lab%202015.md

**Comment by rwaples** [comment]
Will do

**Comment by rwaples** [comment]
Worksheet is nearly updated, 

Outstanding questions:

Metridium spp for dissection?

dissection worksheet references a 'handout provided' during the dissection - what is this?

still have Anthopleura elegantissima in a wet mount? will these be live?

check algal symbiont text: Anthopleura elegantissima?

**Comment by jheare** [comment]
The Handout is in the Cnidarian box and just describes some material about
the metridium/anthropleura.

**Comment by rwaples** [comment]
remove algal symbiont text

check for handout during lab

edit handout for metridium spp text
