### ISSUE TITLE
QP- Lab A readings 

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#16]
@jheare 
What reading material were you considering for the QP lab A work sheet?

**Comment by jheare** [comment]
_The evolutionary and ecological role of heat shock proteins_
Sorenson et al. 2003

_Testing local and global stressor impacts on a coastal foundation species using an
ecologically realistic framework_
Cheng et al. 2015

_Energy homeostasis as an integrative tool for assessing limits of environmental
stress tolerance in aquatic invertebrates_
Sokolova et al. 2012

_MOSAIC PATTERNS OF THERMAL STRESS IN THE ROCKY INTERTIDAL
ZONE: IMPLICATIONS FOR CLIMATE CHANGE_
Helmuth et al. 2006

I figure we can have one person per paper per group read. They can each post a summary on the discussion board and they can discuss what the papers mean in class during Lab B. They can work together to figure out how this relates to their project and how they can use the information to inform their hypothesis.

**Comment by sr320** [comment]
thanks
