### ISSUE TITLE
Rescheduling This Friday Lab Meeting?

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#20]
For our weekly Friday Meeting - Do we need to reschedule as Jake might be getting oysters?

**Comment by jheare** [comment]
Yes, would thursday afternoon after Lab work?

**Comment by sr320** [comment]
Not for me - how about 11am Wednesday?

**Comment by rwaples** [comment]
Wednesday at 11 works for me .

**Comment by jheare** [comment]
Wednesday at 11 works for me as well.
