### ISSUE TITLE
[protip] Simple way to print / render md files 

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#23]
Simply change

https://github.com/sr320/course-fish310-2015/blob/master/Lab%20Worksheets%20MD/Intro%20Lab%202015.md

to 

https://gitprint.com/sr320/course-fish310-2015/blob/master/Lab%20Worksheets%20MD/Intro%20Lab%202015.md

**Comment by jheare** [comment]
Wow that is simple. I've just been printing them using MD pad.
