### ISSUE TITLE
Set-up Gradebook in Canvas

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#24]
We need to set-up a gradebook in Canvas, based on syllabus..

![syllabus_md](https://cloud.githubusercontent.com/assets/4442039/7030544/3c37205c-dd1a-11e4-9f64-d71d107a1778.png)

Each Assignment should be one entry except 

-Quizzes = 10
-Lab Worksheets = 20 
-Lab Practicals = 2

**Comment by jheare** [comment]
Canvas has been updated with the assignments and exams. We can enter the grades on Canvas now for everything.

**Comment by sr320** [comment]
But it maybe too laborous - I do not see easy way to enter in 10 quizzes, 20 WS etc. 

Mayble Catalyst makes more sense?

**Comment by jheare** [comment]
I can create a whole section for quizzes and make them points based. It pretty easy. It took me all of 10 minutes to make all the assignments on the grade book now. As for the worksheets, we are using them as a participation grade in class. So I figure one option with the total percentage works for that. We can subtract points based on the number of labs they miss.

**Comment by jheare** [comment]
I just created a section for all the quizzes. Each quiz is worth 10 points. The entire section will be worth 10%. I can do the same with the exams if you want.

**Comment by sr320** [comment]
If we have time at 11 lets maybe look -
with an eye toward table at top,
before put too much time into it.

thanks

Steven Roberts

**Comment by jheare** [comment]
I just added a column for each lab worksheet. Each work sheet is worth a half a point. Most of them are published. I just wanted to get your opinion before publishing the practice talk and presentation worksheet.

**Comment by sr320** [comment]
Lets hold off publishing these. Lets discuss at Friday meeting next week.

Thanks for setting this up.
