### ISSUE TITLE
qPCR analysis

### ISSUE THREAD

**Issue by rwaples** [sr320/course-fish310-2015#34]
Place to discuss the best way to communicate to the students about analysis of qPCR data.

Open questions:

1) We should post actin data to be used for standardization

2) How should we instruct students run statistics on the data?
- we can't use t-tests on the calculated expression values they are very non-normal.
- We can ask students to log-transform - but then we basically get back the C(T) scale.
- Parametric (t-test on log-transformed data) vs non-parametric (Mann-Whitney)?

3) when normalizing with Actin - we divide the calculated expression value of the target by the expression value Actin, rather than dividing the  C(t), right?  This would be something like subtracting the 

4) should we pay attention to the efficiency value?  Does an efficiency of 100 mean doubling each PCR cycle?  Is this on an absolute or on a scale relative to some other control?

**Comment by sr320** [comment]
1) Sure you can post actin- but would be good to show them how it was determined.

2) Toughy as we can easily confuse students and they might get lost in details ...
Your call - could also go with would need many more reps to do correctly so for this we will just use xxx. understanding its more complicated 

via http://www.biomedcentral.com/1756-0500/5/502

Average Ct (fluorescence-based cycle threshold) values across replicates and average gene efficiencies were calculated with PCR Miner ( http://www.miner.ewindup.info/version2 webcite[10]). Gene expression (R0) was calculated based on the equation R0 = 1/(1 + E)Ct, where E is the average gene efficiency and Ct is the cycle threshold for fluorescence. Each primer pair amplified a single product, as demonstrated by a single melting curve (see Additional file 2). All expression values were normalized to expression of EF1α [GenBank: AB122066]. EF1α did not show differential expression between treatments as verified by a t-test done on expression values of the qPCR run in duplicate. All qPCRs were run in duplicate and significant differences in expression were determined using a linear model with α = 0.05. Box-Cox plots were used to assess skewness of gene expression data and determine if transformations needed to be made. The need to transform the data and the transformation used were determined from the lamda (λ) corresponding to the maximum log likelihood in the Box-Cox plot. If λ = 1 fell within the 95% confidence interval of the maximum log likelihood, then no transformation was used. All statistical analyses were done in R [30].

3) yes GOI exp/actin exp

4) no just ignore eff. for simplicity sake

**Comment by jheare** [comment]
The actin data is posted but I'm not sure which groups did it so I need to confirm the actin data before committing it.

**Comment by rwaples** [comment]
How about we ask them to run t-tests on the C(t) values directly?  we can ask them to plot the expression values to get a sense of the scale of differences.

**Comment by sr320** [comment]
Why not just have them run t-test on expression data - explaining not completely appropriate?

**Comment by rwaples** [comment]
Works for me!

If we have the log-transformed data in hand - I dont think it adds much if any complexity.  the results of the t-test on untransformed expression data will be almost completely determined by the single sample with highest expression value.

We'll try to get the students to get target and normalized expression values - and interpret them any statistics done (on C(t) or expression) will be gravy.  If stats are applied the students should be expected to evaluate their appropriateness.

**Comment by rwaples** [comment]
Both of the groups doing qPCR analysis in the Monday section - were on very much on top of the expression analysis.  I had put together an example workflow,  but it wasn't necessary - they were already there.

The groups may or may report a statistical analysis of the qPCR data - but they seem on top of graphically presenting and interpreting it.  One group had done a t-test of the expression data - I hope they include it their presentation.
