### ISSUE TITLE
Lab Schedule with Lecture schedule

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish310-2015#4]
Lets work on the lab schedule by integrating with Lectures

https://github.com/sr320/course-fish310-2015/blob/master/Syllabus.md

**Comment by jheare** [comment]
No problem. I'm just trying to split up the lab sessions so there is the experiment portion on WTh and the Biology portion on MT. I can reverse that if it works better for you.

**Comment by sr320** [comment]
What do you mean by experiment portion and biology portion?

**Comment by sr320** [comment]
done
